### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by louislva** [jurassix/atom-javascript-refactor#143]
This is kinda annoying, I'd love if it just used regular slashes!

**Comment by jurassix** [comment]
I haven't tested on Windows, I'll give it a go and see what can be done.

**Comment by louislva** [comment]
@jurassix thanks a lot! Really, it means a lot to me!

**Comment by melounek** [comment]
same (maybe bigger issue) here... it refactored the paths to something like this:

`import type { FnType, PacketType } from '..\\..\\Function\\functionReducer'`

**Comment by louislva** [comment]
https://github.com/vladimir-tikhonov/tree-view-copy-relative-path has a setting to just replace backslashes with slashes in their new paths.

I've never developed Atom plugins, but can I give it a shot? (not promising anything though)

**Comment by louislva** [comment]
@jurassix, I think it's the path module in the transform (refactoring-codemods) that's using \ on windows. I'm not familiar with jscodeshift, so I don't know how I would replace all backslashes with forward-slashes as the final "action" before it modifies the file?

**Comment by jurassix** [comment]
@louislva I'll have to check if we are using the [path delimiter](https://nodejs.org/api/path.html#path_path_delimiter) when building up the paths, it already accounts for windows.

**Comment by jurassix** [comment]
Actually I think I see the problem. I'm rewriting paths using [sep](https://nodejs.org/api/path.html#path_path_sep) instead of just using `'/'`. Since these are module paths and not file paths I shouldn't be using a the path separator.

**Comment by jurassix** [comment]
@louislva I've published a fix in v0.6.2, I haven't been able to test it on windows. Can you let me know if it's working or what existing bugs you find. Thanks!

**Comment by louislva** [comment]
@jurassix I greatly appreciate your work, but it's still not working. It still uses double backslashes as before. Thanks a lot!

**Comment by nthgol** [comment]
+1 still double backslash

**Comment by jurassix** [comment]
@louislva @nthgol i've released v0.7.0 I've removed the `isWindows` check and am simply formatting the new paths on path rewrite. Let me know if this version is working.

**Comment by nthgol** [comment]
thanks. Im getting the following install error: 

```
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: refactoring-codemods@0.3.4
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.0, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.4, 0.0.3, 0.0.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'javascript-refactor'
npm ERR! notarget 

```

**Comment by jurassix** [comment]
@nthgol my bad accidentally published to an internal npm registry. I've pushed the 0.3.4 version to npm and even cut a patch for this project just to be safe. v0.7.1

**Comment by nthgol** [comment]
@jurassix it installs, I won't have time to test the backslashes much til later today, keep you posted. thx

**Comment by melounek** [comment]
For me it's working (v0.7.1)... thanks!

**Comment by louislva** [comment]
This works like a charm. Thank you so much @jurassix <3

**Comment by jurassix** [comment]
💯 thanks everyone for confirming!
